/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { ICedarAgreementV0, ICedarAgreementV0Interface } from '../ICedarAgreementV0';

const _abi = [
  {
    inputs: [],
    name: 'acceptTerms',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_address',
        type: 'address',
      },
    ],
    name: 'getAgreementStatus',
    outputs: [
      {
        internalType: 'bool',
        name: 'sig',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bool',
        name: '_status',
        type: 'bool',
      },
    ],
    name: 'setTermsStatus',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_acceptor',
        type: 'address',
      },
      {
        internalType: 'bytes',
        name: '_signature',
        type: 'bytes',
      },
    ],
    name: 'storeTermsAccepted',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'termsActivated',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'userAgreement',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class ICedarAgreementV0__factory {
  static readonly abi = _abi;
  static createInterface(): ICedarAgreementV0Interface {
    return new utils.Interface(_abi) as ICedarAgreementV0Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ICedarAgreementV0 {
    return new Contract(address, _abi, signerOrProvider) as ICedarAgreementV0;
  }
}
